# ref. http://docs.travis-ci.com/user/languages/objective-c/

language: objective-c
osx_image: xcode10.1

before_install:
  - gem install xcpretty

script:
  set -o pipefail &&
  travis_retry
  xcodebuild test
  -workspace CotEditor.xcworkspace
  -scheme CotEditor
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
  ENABLE_HARDENED_RUNTIME=NO
  | xcpretty
